### PR TITLE
Аdd parameter 'numberOfIsolates' 

### PR DESCRIPTION
**Pull request by nikitadol**

### CODE REVIEW

**Comment by Renesanse** [comment]
Hello @nikitadol! Thx for your pr, can you please clean up your pull pr and explain your motivation to add numberOfIsolates parameter? In which cases it is necessary?

**Comment by nikitadol** [comment]
Hi @Renesanse 

> explain your motivation to add numberOfIsolates parameter

In some of my projects, only 1 isolate is needed, since all tasks must be completed one at a time

> clean up your pr

'example' I specifically corrected it so that it does not issue warnings

**Comment by Renesanse** [comment]
@nikitadol  Good point, I agree with your suggestion. I noticed a lot of unnecessary changes not only in example folder
Screenshot 2021-01-08 at 17 23 05. Can I suggest you to split your pr to two different ones? First - numberOfIsolates with test. The second one is pure example only with dart code and Kotlin/iOS code, only if it needs to run application. Thx!

**Comment by Renesanse** [comment]
@nikitadol did you test the case if numberOfIsolates will be greater than available processors count?

**Comment by nikitadol** [comment]
@Renesanse 


> @nikitadol did you test the case if numberOfIsolates will be greater than available processors count?

No

I ran tests in your project - some of them fail

I also noticed that if you run all the tests, then each call to 
```dart 
await Executor (). WarmUp ();
``` 
creates new isolates and as a result, more of them are created than the number of processors is several times

**Pull request closed without merging**
